/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal;

import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author beytu
 */
public class Login extends javax.swing.JFrame {
private static String userName;
private static String password;
private static String url;

    public  String getUrl() {
        return url;
    }

    public  void setUrl(String url) {
        Login.url = url;
    }
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signInButton = new javax.swing.JButton();
        databaseBox = new javax.swing.JComboBox<>();
        comboButton = new javax.swing.JButton();
        tableButton = new javax.swing.JButton();
        tableNames = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        signInButton.setText("SignIn");
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });

        comboButton.setText("List Databases");
        comboButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboButtonActionPerformed(evt);
            }
        });

        tableButton.setText("List Tables");
        tableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(signInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(databaseBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableNames, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(databaseBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(comboButton)
                .addGap(18, 18, 18)
                .addComponent(tableNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(tableButton)
                .addGap(48, 48, 48)
                .addComponent(signInButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
     
       Success Success = new Success();
       Success.setShownTable(tableNames.getSelectedItem().toString());
for(int i =0 ;i<tableNames.getSize().height;i++){
    System.out.println("i:"+i+" "+tableNames.getItemAt(i));
   Success.tablesCombo.addItem(tableNames.getItemAt(i));
    
    
}    
       
    
         try{ 
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           
            Connection con = DriverManager.getConnection(url);
            
                System.out.println("loginde sigIn'e girdi");
                
                JOptionPane.showMessageDialog(null,"Giriş Başarılı");
                Success field = new Success();
                field.setVisible(true);
                setVisible(false);
            
            
          
        
            con.close();
         }
           catch(Exception e){
            JOptionPane.showMessageDialog(null,"Giriş Başarısız");
        }
        
        
       
       
    
    }//GEN-LAST:event_signInButtonActionPerformed

    private void comboButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboButtonActionPerformed

        
        databaseBox.removeAllItems();

        
        
        url="jdbc:sqlserver://localhost:1433;user="+userName+";password="+password;
        System.out.println("addcombo çalışıyor uname + password = "+userName+password);
         
          Connection con = null;
    try {
        con = DriverManager.getConnection(url);
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
            
    try {
        Statement st =con.createStatement();
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
        DatabaseMetaData metadata = null;
    try {
        metadata = con.getMetaData();
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
        ResultSet result = null;
    try {
        result = metadata.getCatalogs();
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
         
    try {
        while (result.next()) {
            String aDBName = result.getString(1);
            System.out.println("database name :  "+aDBName);
            databaseBox.addItem(aDBName);
            System.out.println("add item geçti");
        }      
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
         
    
    
    
    //------------------
    
    
    
    
    
    
    
    
    
    
    }//GEN-LAST:event_comboButtonActionPerformed

   
    private void tableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableButtonActionPerformed
        tableNames.removeAllItems();
        

        
        url="jdbc:sqlserver://localhost:1433;databaseName="+databaseBox.getSelectedItem()+";user="+userName+";password="+password;
       
        System.out.println("tableda user ve pass " +userName + password);
        System.out.println(databaseBox.getSelectedItem());
        Connection con = null;
    try {
        con = DriverManager.getConnection(url);
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }

        String[] types = {"TABLE"};
DatabaseMetaData metadata = null;
    try {
        metadata = con.getMetaData();
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
ResultSet resultSet = null;
    try {
        resultSet = metadata.getTables(null, null, "%", types);
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        while (resultSet.next())
        {
            String tableName = resultSet.getString(3);
            System.out.println(tableName);
            System.out.println(tableName);
            tableNames.addItem(tableName);
        }   // TODO add your handling code here:
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
       
    }//GEN-LAST:event_tableButtonActionPerformed

  
    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        System.out.println("set username girdi");
        this.userName = userName;
        System.out.println(userName+":username");
        
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) throws SQLException {
        this.password = password;
       
    }

   
    /**
     * @param args the command line arguments
     */
   
    
    public static String yazdir(){
        
        
        return url;
    }

    public JComboBox<String> getTableNames() {
        return tableNames;
    }

    public void setTableNames(JComboBox<String> tableNames) {
        this.tableNames = tableNames;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comboButton;
    private static javax.swing.JComboBox<String> databaseBox;
    private javax.swing.JButton signInButton;
    private javax.swing.JButton tableButton;
    private javax.swing.JComboBox<String> tableNames;
    // End of variables declaration//GEN-END:variables

   
   
}
